#!/bin/sh
#
# NAME
#    clean-workspace -- remove python artifacts from current tree.
#
# vim: set ts=2 sw=2 sts=2 et:

echo "Removing environments..."
rm -fr env*
rm -fr .tox

test -d build && {
  echo "Removing build subtree..."
  rm -fr build
}

test -d dist && {
  echo "Removing distributions..."
  rm -fr dist
}

echo "Removing reports and test state..."
test -d htmlcov && rm -fr htmlcov
test -e .coverage && rm .coverage

echo "Removing python caches..."
find . -name '*.pyc' -delete
find . -name '__pycache__' -delete
rm -fr *.egg-info

test -f docker-compose.yml && {
  echo "Cleaning up docker environment..."
  machine=$(docker-machine active)
  eval "$(docker-machine env $machine)"
  docker-compose stop
  docker-compose rm --force
}
