#!/bin/sh
#
# NAME
#    reset-workspace -- clear and rebuild a python workspace
#
# DESCRIPTION
#    Uses *clean-workspace* to remove build cruft before creating
#    the workspace anew.
#
# ENVIRONMENT VARIABLES
#    *PYTHON*
#       Identifies the python interpreter to build the virtual
#       environment with.
#
# vim: set ts=2 sw=2 sts=2 et:

for name in development testing installation
do
  if test -e requires/$name.txt
  then
    req_file=requires/$name.txt
    break
  fi
done

if test -z "$req_file"
then
  echo "This doesn't look much like a Python project to me."
  echo "It is missing requires/{development,testing,installation}.txt."
  echo "You are on your own."
  exit 70
fi

echo "\nCleaning workspace."
clean-workspace 2>&1 | sed 's/^/  /'

python=${PYTHON:-python}
if $python --version 2>&1 | grep -q '2.[67]'
then
  envmod=virtualenv
else
  envmod=venv
fi

echo "\nCreating Python environment."
($python -m$envmod env
 env/bin/pip install -qr $req_file) 2>&1 | sed 's/^/  /'
if test -e bootstrap
then
  echo "\nBootstrapping."
  ./bootstrap 2>&1 | sed 's/^/  /'
fi
echo "\nDone."
